universe = vanilla
executable = /scratch/pratyusava.baral/Modified_Dispersion/src/dispersion/bin/python
arguments = "/scratch/pratyusava.baral/Modified_Dispersion/bilby/scripts/pe.py  $(macroj) --outdir /scratch/pratyusava.baral/Modified_Dispersion/bilby/run_directory/CE_1p0MW_AplusCoat_flow10/A0/results/$(Process)  --A_max 1e-1  --sample-CE-arrival-time  --time_prior_halfwidth 0.001  --flow 10   --A1  --asd_CE40low  --nlive 500   --nact 60   --npool 16   --dlogz 0.01   --chi 10   --epsilon 0.1   -1245   --mode_array '[[2,2], [3,2], [3,3], [4,4]]'"
accounting_group = ligo.dev.o4.cbc.pe.lalinferenceonline
request_memory = 6000
request_disk = 25000K
request_cpus = 4
notification = never
output = /scratch/pratyusava.baral/Modified_Dispersion/bilby/run_directory/CE_1p0MW_AplusCoat_flow10/A0/logs/$(Process).out
error = /scratch/pratyusava.baral/Modified_Dispersion/bilby/run_directory/CE_1p0MW_AplusCoat_flow10/A0/logs/$(Process).err
log = /scratch/pratyusava.baral/Modified_Dispersion/bilby/run_directory/CE_1p0MW_AplusCoat_flow10/A0/logs/$(Process).log
queue macroj from ../index.txt
